/*
 * Copyright (c) ALRIGROUP and its affiliates.
 *
 * This code is licensed under the ARGLR - ALRI GROUP LICENSE RESERVED
 * found in the LICENSE file in the root directory of this source tree
 * and at: https://github.com/alrigroup/licenses/tree/main
 */

#ifndef ARWS_WEB_DATA_H
#define ARWS_WEB_DATA_H

static const char *arws_404_html =
    "<!DOCTYPE html>\r\n"
    "<html lang=\"pt-BR\">\r\n"
    "<head>\r\n"
    "<meta charset=\"UTF-8\">\r\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
    "<title>404 - Página não encontrada | ALRI GROUP</title>\r\n"
    "<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"https://cdn.alrigroup.com/favicon-32x32.png\">\r\n"
    "<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"https://cdn.alrigroup.com/favicon-16x16.png\">\r\n"
    "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n"
    "<style>\r\n"
    ":root {\r\n"
    "    --bg: #020202;\r\n"
    "    --surface: rgba(17, 17, 17, 0.4);\r\n"
    "    --border: rgba(255, 255, 255, 0.08);\r\n"
    "    --text-main: #ffffff;\r\n"
    "    --text-muted: #a0a0a0;\r\n"
    "    --neon-red: #ff003c;\r\n"
    "    --neon-red-glow: rgba(255, 0, 60, 0.5);\r\n"
    "    --font-sans: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\r\n"
    "    --font-mono: 'Courier New', Courier, monospace;\r\n"
    "}\r\n"
    "* { margin: 0; padding: 0; box-sizing: border-box; }\r\n"
    "body {\r\n"
    "    background-color: var(--bg);\r\n"
    "    color: var(--text-main);\r\n"
    "    font-family: var(--font-sans);\r\n"
    "    line-height: 1.6;\r\n"
    "    overflow-x: hidden;\r\n"
    "    min-height: 100vh;\r\n"
    "    display: flex;\r\n"
    "    flex-direction: column;\r\n"
    "    justify-content: space-between;\r\n"
    "}\r\n"
    ".navbar {\r\n"
    "    padding: 1.5rem 5%;\r\n"
    "    display: flex;\r\n"
    "    justify-content: space-between;\r\n"
    "    align-items: center;\r\n"
    "    border-bottom: 1px solid var(--border);\r\n"
    "    background: rgba(2, 2, 2, 0.6);\r\n"
    "    position: sticky;\r\n"
    "    top: 0;\r\n"
    "    z-index: 100;\r\n"
    "    backdrop-filter: blur(12px);\r\n"
    "    -webkit-backdrop-filter: blur(12px);\r\n"
    "}\r\n"
    ".logo { font-size: 1.5rem; font-weight: 800; letter-spacing: 2px; }\r\n"
    ".logo span { color: var(--text-muted); font-weight: 400; }\r\n"
    "#hero {\r\n"
    "    position: relative;\r\n"
    "    min-height: 70vh;\r\n"
    "    display: flex;\r\n"
    "    align-items: center;\r\n"
    "    justify-content: center;\r\n"
    "    text-align: center;\r\n"
    "    padding: 4rem 2rem;\r\n"
    "}\r\n"
    ".bg-grid {\r\n"
    "    position: absolute;\r\n"
    "    top: 0; left: 0; width: 100%; height: 100%;\r\n"
    "    background-image: linear-gradient(var(--border) 1px, transparent 1px), linear-gradient(90deg, var(--border) 1px, transparent 1px);\r\n"
    "    background-size: 50px 50px;\r\n"
    "    opacity: 0.2;\r\n"
    "    z-index: 1;\r\n"
    "}\r\n"
    ".glow-orb {\r\n"
    "    position: absolute;\r\n"
    "    top: 50%; left: 50%;\r\n"
    "    transform: translate(-50%, -50%);\r\n"
    "    width: 350px; height: 350px;\r\n"
    "    background: radial-gradient(circle, var(--neon-red-glow) 0%, transparent 70%);\r\n"
    "    z-index: 2;\r\n"
    "    pointer-events: none;\r\n"
    "    animation: pulse 4s infinite alternate ease-in-out;\r\n"
    "}\r\n"
    "@keyframes pulse {\r\n"
    "    0% { transform: translate(-50%, -50%) scale(0.8); opacity: 0.4; }\r\n"
    "    100% { transform: translate(-50%, -50%) scale(1.2); opacity: 0.8; }\r\n"
    "}\r\n"
    ".hero-content {\r\n"
    "    position: relative;\r\n"
    "    z-index: 3;\r\n"
    "    max-width: 650px;\r\n"
    "}\r\n"
    ".text-gradient {\r\n"
    "    background: linear-gradient(90deg, var(--text-main) 0%, var(--neon-red) 100%);\r\n"
    "    -webkit-background-clip: text;\r\n"
    "    -webkit-text-fill-color: transparent;\r\n"
    "    text-shadow: 0 0 20px var(--neon-red-glow);\r\n"
    "}\r\n"
    ".hero-content h1 {\r\n"
    "    font-size: clamp(2.5rem, 5vw, 4.5rem);\r\n"
    "    font-weight: 900;\r\n"
    "    letter-spacing: -1px;\r\n"
    "    margin-bottom: 1rem;\r\n"
    "}\r\n"
    ".hero-content p {\r\n"
    "    color: var(--text-muted);\r\n"
    "    font-size: 1.1rem;\r\n"
    "    margin-bottom: 2rem;\r\n"
    "}\r\n"
    ".cta-button {\r\n"
    "    display: inline-block;\r\n"
    "    background: var(--neon-red);\r\n"
    "    color: #fff;\r\n"
    "    padding: 0.8rem 2rem;\r\n"
    "    border-radius: 4px;\r\n"
    "    text-decoration: none;\r\n"
    "    font-weight: 600;\r\n"
    "    letter-spacing: 1px;\r\n"
    "    transition: all 0.3s ease;\r\n"
    "    box-shadow: 0 0 15px var(--neon-red-glow);\r\n"
    "}\r\n"
    ".cta-button:hover {\r\n"
    "    transform: translateY(-2px);\r\n"
    "    box-shadow: 0 0 25px var(--neon-red);\r\n"
    "}\r\n"
    "footer {\r\n"
    "    padding: 2rem 5%;\r\n"
    "    border-top: 1px solid var(--border);\r\n"
    "    text-align: center;\r\n"
    "    background: #000000;\r\n"
    "}\r\n"
    ".footer-socials { display: flex; justify-content: center; gap: 1.5rem; margin-bottom: 1rem; }\r\n"
    ".footer-socials a { color: var(--text-muted); font-size: 1.2rem; transition: color 0.3s ease; }\r\n"
    ".footer-socials a:hover { color: var(--neon-red); }\r\n"
    ".footer-quote { color: var(--text-muted); font-size: 0.85rem; font-style: italic; margin-bottom: 0.5rem; }\r\n"
    ".footer-copy { color: rgba(255,255,255,0.3); font-size: 0.75rem; }\r\n"
    ".fade-in { opacity: 0; transform: translateY(20px); transition: opacity 0.8s ease, transform 0.8s ease; }\r\n"
    ".fade-in.visible { opacity: 1; transform: translateY(0); }\r\n"
    "</style>\r\n"
    "</head>\r\n"
    "<body>\r\n"
    "<nav class=\"navbar\"><div class=\"logo\">ALRI<span>GROUP</span></div></nav>\r\n"
    "<main>\r\n"
    "<section id=\"hero\">\r\n"
    "<div class=\"bg-grid\"></div>\r\n"
    "<div class=\"glow-orb\"></div>\r\n"
    "<div class=\"hero-content fade-in visible\">\r\n"
    "<img src=\"https://cdn.alrigroup.com/ALRI-SF-W.png\" width=\"250\" alt=\"ALRI Group Logo\" style=\"margin-bottom:2rem;filter:drop-shadow(0 0 10px rgba(255,255,255,0.1))\">\r\n"
    "<h1><span class=\"text-gradient\">404</span></h1>\r\n"
    "<p>O recurso que você está procurando não existe ou foi movido para outro endereço.</p>\r\n"
    "<a href=\"/\" class=\"cta-button\">Voltar ao Início</a>\r\n"
    "</div>\r\n"
    "</section>\r\n"
    "</main>\r\n"
    "<footer>\r\n"
    "<div class=\"footer-socials\">\r\n"
    "<a href=\"https://www.instagram.com/alrigroup\" target=\"_blank\" title=\"Instagram\"><i class=\"fab fa-instagram\"></i></a>\r\n"
    "<a href=\"https://dsc.gg/alrigroup\" target=\"_blank\" title=\"Discord\"><i class=\"fab fa-discord\"></i></a>\r\n"
    "<a href=\"https://github.com/alrigroup\" target=\"_blank\" title=\"GitHub\"><i class=\"fab fa-github\"></i></a>\r\n"
    "</div>\r\n"
    "<p class=\"footer-quote\">\"Building the future, one line of code at a time.\"</p>\r\n"
    "<p class=\"footer-copy\">&copy; 2020-2026 ALRI GROUP. All rights reserved.</p>\r\n"
    "</footer>\r\n"
    "<script>\r\n"
    "document.addEventListener('DOMContentLoaded', function() {\r\n"
    "    var fade = document.querySelector('.fade-in');\r\n"
    "    if (fade) fade.classList.add('visible');\r\n"
    "});\r\n"
    "</script>\r\n"
    "</body></html>";

static const char *arws_maintenance_html =
    "<!DOCTYPE html>\r\n"
    "<html lang=\"pt-BR\">\r\n"
    "<head>\r\n"
    "<meta charset=\"UTF-8\">\r\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
    "<title>Em Manutenção | ALRI GROUP</title>\r\n"
    "<link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"https://cdn.alrigroup.com/favicon-32x32.png\">\r\n"
    "<link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"https://cdn.alrigroup.com/favicon-16x16.png\">\r\n"
    "<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n"
    "<style>\r\n"
    ":root {\r\n"
    "    --bg: #020202;\r\n"
    "    --surface: rgba(17, 17, 17, 0.4);\r\n"
    "    --border: rgba(255, 255, 255, 0.08);\r\n"
    "    --text-main: #ffffff;\r\n"
    "    --text-muted: #a0a0a0;\r\n"
    "    --neon-red: #ff003c;\r\n"
    "    --neon-red-glow: rgba(255, 0, 60, 0.5);\r\n"
    "    --font-sans: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\r\n"
    "    --font-mono: 'Courier New', Courier, monospace;\r\n"
    "}\r\n"
    "* { margin: 0; padding: 0; box-sizing: border-box; }\r\n"
    "body {\r\n"
    "    background-color: var(--bg);\r\n"
    "    color: var(--text-main);\r\n"
    "    font-family: var(--font-sans);\r\n"
    "    line-height: 1.6;\r\n"
    "    overflow-x: hidden;\r\n"
    "    min-height: 100vh;\r\n"
    "    display: flex;\r\n"
    "    flex-direction: column;\r\n"
    "    justify-content: space-between;\r\n"
    "}\r\n"
    ".navbar {\r\n"
    "    padding: 1.5rem 5%;\r\n"
    "    display: flex;\r\n"
    "    justify-content: space-between;\r\n"
    "    align-items: center;\r\n"
    "    border-bottom: 1px solid var(--border);\r\n"
    "    background: rgba(2, 2, 2, 0.6);\r\n"
    "    position: sticky;\r\n"
    "    top: 0;\r\n"
    "    z-index: 100;\r\n"
    "    backdrop-filter: blur(12px);\r\n"
    "    -webkit-backdrop-filter: blur(12px);\r\n"
    "}\r\n"
    ".logo { font-size: 1.5rem; font-weight: 800; letter-spacing: 2px; }\r\n"
    ".logo span { color: var(--text-muted); font-weight: 400; }\r\n"
    "#hero {\r\n"
    "    position: relative;\r\n"
    "    min-height: 70vh;\r\n"
    "    display: flex;\r\n"
    "    align-items: center;\r\n"
    "    justify-content: center;\r\n"
    "    text-align: center;\r\n"
    "    padding: 4rem 2rem;\r\n"
    "}\r\n"
    ".bg-grid {\r\n"
    "    position: absolute;\r\n"
    "    top: 0; left: 0; width: 100%; height: 100%;\r\n"
    "    background-image: linear-gradient(var(--border) 1px, transparent 1px), linear-gradient(90deg, var(--border) 1px, transparent 1px);\r\n"
    "    background-size: 50px 50px;\r\n"
    "    opacity: 0.2;\r\n"
    "    z-index: 1;\r\n"
    "}\r\n"
    ".glow-orb {\r\n"
    "    position: absolute;\r\n"
    "    top: 50%; left: 50%;\r\n"
    "    transform: translate(-50%, -50%);\r\n"
    "    width: 350px; height: 350px;\r\n"
    "    background: radial-gradient(circle, var(--neon-red-glow) 0%, transparent 70%);\r\n"
    "    z-index: 2;\r\n"
    "    pointer-events: none;\r\n"
    "    animation: pulse 4s infinite alternate ease-in-out;\r\n"
    "}\r\n"
    "@keyframes pulse {\r\n"
    "    0% { transform: translate(-50%, -50%) scale(0.8); opacity: 0.4; }\r\n"
    "    100% { transform: translate(-50%, -50%) scale(1.2); opacity: 0.8; }\r\n"
    "}\r\n"
    ".hero-content {\r\n"
    "    position: relative;\r\n"
    "    z-index: 3;\r\n"
    "    max-width: 650px;\r\n"
    "}\r\n"
    ".text-gradient {\r\n"
    "    background: linear-gradient(90deg, var(--text-main) 0%, var(--neon-red) 100%);\r\n"
    "    -webkit-background-clip: text;\r\n"
    "    -webkit-text-fill-color: transparent;\r\n"
    "    text-shadow: 0 0 20px var(--neon-red-glow);\r\n"
    "}\r\n"
    ".hero-content h1 {\r\n"
    "    font-size: clamp(2.5rem, 5vw, 4.5rem);\r\n"
    "    font-weight: 900;\r\n"
    "    letter-spacing: -1px;\r\n"
    "    margin-bottom: 1rem;\r\n"
    "}\r\n"
    ".hero-content p {\r\n"
    "    color: var(--text-muted);\r\n"
    "    font-size: 1.1rem;\r\n"
    "    margin-bottom: 2rem;\r\n"
    "}\r\n"
    ".cta-button {\r\n"
    "    display: inline-block;\r\n"
    "    background: var(--neon-red);\r\n"
    "    color: #fff;\r\n"
    "    padding: 0.8rem 2rem;\r\n"
    "    border-radius: 4px;\r\n"
    "    text-decoration: none;\r\n"
    "    font-weight: 600;\r\n"
    "    letter-spacing: 1px;\r\n"
    "    transition: all 0.3s ease;\r\n"
    "    box-shadow: 0 0 15px var(--neon-red-glow);\r\n"
    "}\r\n"
    ".cta-button:hover {\r\n"
    "    transform: translateY(-2px);\r\n"
    "    box-shadow: 0 0 25px var(--neon-red);\r\n"
    "}\r\n"
    "footer {\r\n"
    "    padding: 2rem 5%;\r\n"
    "    border-top: 1px solid var(--border);\r\n"
    "    text-align: center;\r\n"
    "    background: #000000;\r\n"
    "}\r\n"
    ".footer-socials { display: flex; justify-content: center; gap: 1.5rem; margin-bottom: 1rem; }\r\n"
    ".footer-socials a { color: var(--text-muted); font-size: 1.2rem; transition: color 0.3s ease; }\r\n"
    ".footer-socials a:hover { color: var(--neon-red); }\r\n"
    ".footer-quote { color: var(--text-muted); font-size: 0.85rem; font-style: italic; margin-bottom: 0.5rem; }\r\n"
    ".footer-copy { color: rgba(255,255,255,0.3); font-size: 0.75rem; }\r\n"
    ".fade-in { opacity: 0; transform: translateY(20px); transition: opacity 0.8s ease, transform 0.8s ease; }\r\n"
    ".fade-in.visible { opacity: 1; transform: translateY(0); }\r\n"
    "</style>\r\n"
    "</head>\r\n"
    "<body>\r\n"
    "<nav class=\"navbar\"><div class=\"logo\">ALRI<span>GROUP</span></div></nav>\r\n"
    "<main>\r\n"
    "<section id=\"hero\">\r\n"
    "<div class=\"bg-grid\"></div>\r\n"
    "<div class=\"glow-orb\"></div>\r\n"
    "<div class=\"hero-content fade-in visible\">\r\n"
    "<img src=\"https://cdn.alrigroup.com/ALRI-SF-W.png\" width=\"250\" alt=\"ALRI Group Logo\" style=\"margin-bottom:2rem;filter:drop-shadow(0 0 10px rgba(255,255,255,0.1))\">\r\n"
    "<h1><span class=\"text-gradient\">EM MANUTENÇÃO</span></h1>\r\n"
    "<p>O sistema está temporariamente indisponível para manutenção. Tente novamente mais tarde.</p>\r\n"
    "<a href=\"/\" class=\"cta-button\">Voltar ao Início</a>\r\n"
    "</div>\r\n"
    "</section>\r\n"
    "</main>\r\n"
    "<footer>\r\n"
    "<div class=\"footer-socials\">\r\n"
    "<a href=\"https://www.instagram.com/alrigroup\" target=\"_blank\" title=\"Instagram\"><i class=\"fab fa-instagram\"></i></a>\r\n"
    "<a href=\"https://dsc.gg/alrigroup\" target=\"_blank\" title=\"Discord\"><i class=\"fab fa-discord\"></i></a>\r\n"
    "<a href=\"https://github.com/alrigroup\" target=\"_blank\" title=\"GitHub\"><i class=\"fab fa-github\"></i></a>\r\n"
    "</div>\r\n"
    "<p class=\"footer-quote\">\"Building the future, one line of code at a time.\"</p>\r\n"
    "<p class=\"footer-copy\">&copy; 2020-2026 ALRI GROUP. All rights reserved.</p>\r\n"
    "</footer>\r\n"
    "<script>\r\n"
    "document.addEventListener('DOMContentLoaded', function() {\r\n"
    "    var fade = document.querySelector('.fade-in');\r\n"
    "    if (fade) fade.classList.add('visible');\r\n"
    "});\r\n"
    "</script>\r\n"
    "</body></html>";

#endif